
CREATE TABLE `spring_session` (
  `PRIMARY_ID` char(36) COLLATE utf8_bin NOT NULL,
  `SESSION_ID` char(36) COLLATE utf8_bin NOT NULL,
  `CREATION_TIME` bigint(20) NOT NULL,
  `LAST_ACCESS_TIME` bigint(20) NOT NULL,
  `MAX_INACTIVE_INTERVAL` int(11) NOT NULL,
  `EXPIRY_TIME` bigint(20) NOT NULL,
  `PRINCIPAL_NAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`PRIMARY_ID`),
  UNIQUE KEY `SPRING_SESSION_IX1` (`SESSION_ID`),
  KEY `SPRING_SESSION_IX2` (`EXPIRY_TIME`),
  KEY `SPRING_SESSION_IX3` (`PRINCIPAL_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `spring_session_attributes` (
  `SESSION_PRIMARY_ID` char(36) COLLATE utf8_bin NOT NULL,
  `ATTRIBUTE_NAME` varchar(200) COLLATE utf8_bin NOT NULL,
  `ATTRIBUTE_BYTES` blob NOT NULL,
  PRIMARY KEY (`SESSION_PRIMARY_ID`,`ATTRIBUTE_NAME`),
  KEY `SPRING_SESSION_ATTRIBUTES_IX1` (`SESSION_PRIMARY_ID`),
  CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK` FOREIGN KEY (`SESSION_PRIMARY_ID`) REFERENCES `spring_session` (`PRIMARY_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


create table P_USERS
(
  ID                INT UNSIGNED NOT NULL AUTO_INCREMENT,
  LOGINNAME         VARCHAR(128) not null,
  PASSWORD          VARCHAR(128) not null,
  ENABLED           CHAR(1) default 'Y',
  LAST_UPDATE_DATE  DATETIME,
  LAST_UPDATED_BY   VARCHAR(128),
  CREATION_DATE     DATETIME,
  CREATED_BY        VARCHAR(128),
  PRIMARY KEY (ID)
);


CREATE TABLE P_RESOURCES
(
  ID                INT UNSIGNED NOT NULL  AUTO_INCREMENT,
  IDENTIFICATION    VARCHAR(1024) NOT NULL COMMENT '受保护的资源定义,例如URL,业务层方法等。 ',
  R_TYPE     		CHAR(32)	   NOT NULL COMMENT 'URL : URL层资源，  METHOD : 方法层资源， DAO ： DAO层资源 ',
  ENABLE        	CHAR(1)	 DEFAULT 'Y'	 COMMENT 'Y ： 资源有效， N ： 资源无效 ',  
  DESCRIPTION       VARCHAR(1000)			 COMMENT '备注信息 ',  
  PRIMARY KEY (ID)
);

CREATE TABLE P_RES_ATTRIBUTE
(
  ID                INT UNSIGNED NOT NULL  AUTO_INCREMENT,
  NAME              VARCHAR(128)			 COMMENT '受保护的资源相关的属性 ',  
  A_TYPE     		CHAR(32)	 NOT NULL	 DEFAULT 'ROLE_' COMMENT 'ROLE : 角色类属性 ',
  ENABLE        	CHAR(1)	 DEFAULT 'Y'	 COMMENT 'Y ： 资源有效， N ： 资源无效 ',  
  MEMO        		VARCHAR(2000)			 COMMENT '备注信息 ',  
  PRIMARY KEY (ID)
);

CREATE TABLE P_RES_ATTR_MAP
(
  ID                INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ATTRIBUTE_ID     	INT NOT NULL,
  RESOURCE_ID       INT NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY RES_ATTR_MAP_U1 (RESOURCE_ID, ATTRIBUTE_ID)
);

create table P_USER_PERMISSION
(
  ID                INT UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID         	INT not null,
  RES_ATTRIBUTE_ID  INT not null,
  PRIMARY KEY (ID)
);









---------------------以下可删除--------------------------


CREATE TABLE `test_user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;